export const measurementVariables = [
  {
    id: 1,
    defaultValue: 1000,
    unit: "mm²",
    description: "Nominal surface area of cone tip",
    category: "equipment",
    dataType: "float",
  },
  {
    id: 2,
    defaultValue: 15000,
    unit: "mm²",
    description: "Nominal surface area of friction sleeve",
    category: "equipment",
    dataType: "float",
  },
  {
    id: 3,
    defaultValue: null,
    unit: "-",
    description: "Net surface area quotient of cone tip",
    category: "equipment",
    dataType: "float",
  },
  {
    id: 4,
    defaultValue: null,
    unit: "-",
    description: "Net surface area quotient of friction sleeve",
    category: "equipment",
    dataType: "float",
  },
  {
    id: 5,
    defaultValue: 100,
    unit: "mm",
    description: "Distance of cone to centre of friction sleeve",
    category: "equipment",
    dataType: "float",
  },
  {
    id: 6,
    defaultValue: null,
    unit: "-",
    description: "Friction present",
    category: "capabilities",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 7,
    defaultValue: null,
    unit: "-",
    description: "PPT u1 present",
    category: "capabilities",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 8,
    defaultValue: null,
    unit: "-",
    description: "PPT u2 present",
    category: "capabilities",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 9,
    defaultValue: null,
    unit: "-",
    description: "PPT u3 present",
    category: "capabilities",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 10,
    defaultValue: null,
    unit: "-",
    description: "Inclination measurement present",
    category: "capabilities",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 11,
    defaultValue: null,
    unit: "-",
    description: "Use of back-flow compensator",
    category: "equipment",
    dataType: "enum",
    options: [
      { value: 0, meaning: "no" },
      { value: 1, meaning: "yes" },
    ],
  },
  {
    id: 12,
    defaultValue: null,
    unit: "-",
    description: "Type of cone penetration test",
    category: "test_type",
    dataType: "enum",
    options: [
      { value: 0, meaning: "electronic penetration test" },
      { value: 1, meaning: "mechanical discontinue" },
      { value: 2, meaning: "mechanical continue" },
    ],
  },
  {
    id: 13,
    defaultValue: null,
    unit: "m",
    description: "Pre-excavated depth",
    category: "site_conditions",
    dataType: "float",
  },
  {
    id: 14,
    defaultValue: null,
    unit: "m",
    description:
      "Groundwater level (with respect to datum of height system in ZID)",
    category: "site_conditions",
    dataType: "float",
  },
  {
    id: 15,
    defaultValue: null,
    unit: "m",
    description: "Water depth (for offshore activities)",
    category: "site_conditions",
    dataType: "float",
  },
  {
    id: 16,
    defaultValue: null,
    unit: "m",
    description: "End depth of penetration test",
    category: "test_execution",
    dataType: "float",
  },
  {
    id: 17,
    defaultValue: null,
    unit: "-",
    description: "Stop criteria",
    category: "test_execution",
    dataType: "enum",
    options: [
      { value: 0, meaning: "end depth reached" },
      { value: 1, meaning: "max. penetration force" },
      { value: 2, meaning: "cone value" },
      { value: 3, meaning: "max. friction value" },
      { value: 4, meaning: "max. PPT value" },
      { value: 5, meaning: "max. inclination value" },
      { value: 6, meaning: "obstacle" },
      { value: 7, meaning: "danger of buckling" },
    ],
  },
  {
    id: 20,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement of cone before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 21,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement of cone after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 22,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement friction before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 23,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement friction after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 24,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u1 before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 25,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u1 after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 26,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u2 before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 27,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u2 after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 28,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u3 before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 29,
    defaultValue: null,
    unit: "MPa",
    description: "Zero measurement PPT u3 after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 30,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 31,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 32,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination NS before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 33,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination NS after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 34,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination EW before penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 35,
    defaultValue: null,
    unit: "degrees",
    description: "Zero measurement inclination EW after penetration test",
    category: "calibration",
    dataType: "float",
  },
  {
    id: 41,
    defaultValue: null,
    unit: "km",
    description: "Mileage",
    category: "location",
    dataType: "float",
  },
  {
    id: 42,
    defaultValue: null,
    unit: "degrees",
    description: "Orientation between X axis inclination and North",
    category: "location",
    dataType: "float",
  },
] as const;

export const measurementTextIds = {
  1: { description: "Client", category: "project_info" },
  2: { description: "Name of the project", category: "project_info" },
  3: { description: "Name of the location", category: "project_info" },
  4: { description: "Cone type and serial number", category: "equipment" },
  5: {
    description: "Mass and geometry of probe apparatus, including anchoring",
    category: "equipment",
  },
  6: {
    description: "Applied standard, including class",
    category: "standards",
  },
  7: { description: "Own coordinate system", category: "coordinates" },
  8: { description: "Own reference level", category: "coordinates" },
  9: {
    description: "Fixed horizontal level",
    category: "coordinates",
  },
  10: {
    description:
      "Orientation direction biaxial inclination measurement (N-direction)",
    category: "measurements",
  },
  11: { description: "Unusual circumstances", category: "conditions" },
  12: { description: "Reserved for future use", category: "reserved" },
  13: { description: "Reserved for future use", category: "reserved" },
  14: { description: "Reserved for future use", category: "reserved" },
  15: { description: "Reserved for future use", category: "reserved" },
  16: { description: "Reserved for future use", category: "reserved" },
  17: { description: "Reserved for future use", category: "reserved" },
  18: { description: "Reserved for future use", category: "reserved" },
  19: { description: "Reserved for future use", category: "reserved" },
  20: {
    description: "Correction method for zero drift",
    category: "processing",
  },
  21: {
    description: "Method for processing interruptions",
    category: "processing",
  },
  22: { description: "Remarks", category: "general" },
  23: { description: "Remarks", category: "general" },
  24: { description: "Reserved for future use", category: "reserved" },
  25: { description: "Reserved for future use", category: "reserved" },
  26: { description: "Reserved for future use", category: "reserved" },
  27: { description: "Reserved for future use", category: "reserved" },
  28: { description: "Reserved for future use", category: "reserved" },
  29: { description: "Reserved for future use", category: "reserved" },
  30: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  31: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  32: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  33: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  34: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  35: {
    description: "Calculation formula or reference for column number",
    category: "calculations",
  },
  36: { description: "Reserved for future use", category: "reserved" },
  37: { description: "Reserved for future use", category: "reserved" },
  38: { description: "Reserved for future use", category: "reserved" },
  39: { description: "Reserved for future use", category: "reserved" },
  40: { description: "Reserved for future use", category: "reserved" },
  41: {
    description: "Highway, railway or dike code",
    category: "infrastructure",
  },
  42: {
    description: "Method for determination of ZID (height)",
    category: "coordinates",
    standardizedCodes: {
      MMET: "Measured, surveying",
      MDGP: "Measured, differential GPS",
      MGOV: "Measured, other methods",
      MH10: "Estimated, contour map 1:10.000",
      MT25: "Estimated, Topographic map 1:25.000",
      MT50: "Estimated, Topographic map 1:50.000",
      MAHN: "Estimated, 'Actueel Hoogtebestand Nederland'",
      MSOV: "Estimated, other methods",
      MONB: "Estimated, unknown method",
      MFIC: "Fictive value",
    },
  },
  43: {
    description: "Method for determination of XYID (position)",
    category: "coordinates",
    standardizedCodes: {
      LMET: "Measured, surveying",
      LGPS: "Measured, GPS",
      LDGM: "Measured, diff. GPS, > 5 m",
      LDGN: "Measured, diff. GPS, between 1 and 5 m",
      LDGZ: "Measured, diff. GPS, < 1m",
      LGOV: "Measured, other methods",
      LT10: "Estimated, Topographic map 1:10.000",
      LT25: "Estimated, Topographic map 1:25.000",
      LT50: "Estimated, Topographic map 1:50.000",
      LD01: "Estimated, detailed map 1:100",
      LD02: "Estimated, detailed map 1:200",
      LD05: "Estimated, detailed map 1:500",
      LD10: "Estimated, detailed map 1:1000",
      LD25: "Estimated, detailed map 1:2500",
      LSOV: "Estimated, other methods",
      LONB: "Estimated, method unknown",
    },
  },
  44: {
    description: "Orientation of X axis of inclination measurement",
    category: "measurements",
  },
} as const;

export type MeasurementVariable = (typeof measurementVariables)[number];
export type MeasurementTextId = keyof typeof measurementTextIds;
